library(broom)
library(furrr)
library(future)
library(Formula)
library(modelr)
library(glmnet)
library(grf)

library(here)
root <- here()

source(file.path(root, "code", "functions", "crossfit", "R", "dml_summary.R"))
source(file.path(root, "code", "functions", "crossfit", "R", "dml.R"))
source(file.path(root, "code", "functions", "crossfit", "R", "moments.R"))
source(file.path(root, "code", "functions", "crossfit", "R", "utils.R"))

.S3method("coef", "dml", coef.dml)
.S3method("fitted", "dml", fitted.dml)
.S3method("glance", "dml", glance.dml)
.S3method("print", "dml", print.dml)
.S3method("print", "summary.dml", summary.dml)
.S3method("summary", "dml", summary.dml)
.S3method("tidy", "dml", tidy.dml)
.S3method("vcov", "dml", vcov.dml)
